### ISSUE TITLE
Initialize experiment/status

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#15]
**Is your feature request related to a problem? Please describe.**
Controller needs to update the status field after the initial creation of the experiment.

**Describe the solution you'd like**
Iteration count and phase of the experiment needs to be set by controller.

**Describe alternatives you've considered**
None.

**Additional context**
See [here](https://github.com/iter8-tools/iter8-kfserving/blob/main/samples/experiments/progressivecanaryrollout-iteration-one.yaml) for an example.

**Comment by kalantar** [comment]
done
