### ISSUE TITLE
Accept valid metrics cr

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/etc3#16]
**Is your feature request related to a problem? Please describe.**
Accept valid metrics cr. Reject others.

**Describe the solution you'd like**
Define go types and implement methods to set default values.

**Describe alternatives you've considered**
None

**Additional context**
Metric CRs for iter8-kfserving package are [here](https://github.com/iter8-tools/iter8-kfserving/tree/main/resources/iter8-kfserving-metrics)

**Comment by sriumcp** [comment]
Since no controller watches for metrics CR, there is no additional work here.
