### ISSUE TITLE
[BUG] When a task runner job fails, etc3 does not record the failure of the task runner job

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#205]
**Describe the bug**
When a task runner job fails, etc3 does not record the failure of the task runner job. Instead, it simply says that the experiment has been completed.

**To Reproduce**
Create any experiment with a task that is designed to fail, example exec task with exit 1 command in it.

**Expected behavior**
etc3 needs to record in status (and stage) that experiment is complete but with failure.

**Comment by kalantar** [comment]
Fixed by #204
