### ISSUE TITLE
Change `sample_size` in metric.spec to camel case instead of snake case

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#76]
**Is your feature request related to a problem? Please describe.**
Most of the field names use camel case convention while iter8 metric's sample_size uses snake case. It is better to fix this for uniformity.

**Describe the solution you'd like**
Change `sample_size` in metric.spec to camel case instead of snake case

**Comment by kalantar** [comment]
@sriumcp @sushmarchandran This is relatively straightforward from a etc3 perspective. One line of code changes (and its consequences in crd yaml and generated code. However, it seems to me that the impact is in any test cases, examples and documentation. How should we address?

**Comment by kalantar** [comment]
Issue https://github.com/iter8-tools/etc3/issues/29 will have similar impact. Should discuss together.
