### ISSUE TITLE
Support fixed splits in experiment CRs

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#9]
**Is your feature request related to a problem? Please describe.**
Ensure that experiment CRs support fixed splits. This is useful when analytics is used purely for assessment and final rollout decisions (i.e., winner identification) and not for traffic splitting.

**Describe the solution you'd like**
Analytics engine config needs to support the following type and associated split clause.
```
type: fixed-split
split:
  default: 20
  canary: 80
```

**Describe alternatives you've considered**
1. Leave out fixed splits altogether (can be done as part of the experiment set up).
2. Specify splits as part of versions -- this might still be a useful option and worth revisiting.

**Comment by kalantar** [comment]
@sushmarchandran did this, no?

**Comment by sushmarchandran** [comment]
@kalantar Yes this is done. The yamls are in the iter8-knative repository
